# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6918ba82a2d63eebad71b52d193013ce3983681d44351426b1ec8524e9683cac81724c7c2dc6ba9d271568abe0e9d14bf75185e16cd408c45a6f4ed2ff2716

test:
  secret_key_base: ecfba7e95ff898d1782c30fb98c7fd3d68838ecc31cec0ff5dba7e06930fcbc25a37bd027987acdfb4ccd9863fa1b58b5b0928cbcd81023e38abe6682c5c92cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
